using System;

namespace NeuralNetwork
{
    class Neuron
        {
                private double[] weights;
                        private double bias;
                                private ActivationFunction activationFunction;

                                        public Neuron(int numInputs, ActivationFunction activationFunction)
                                                {
                                                            this.activationFunction = activationFunction;
                                                                        weights = new double[numInputs];
                                                                                    Random rnd = new Random();

                                                                                                for (int i = 0; i < numInputs; i++)
                                                                                                            {
                                                                                                                            weights[i] = rnd.NextDouble();
                                                                                                                                        }

                                                                                                                                                    bias = rnd.NextDouble();
                                                                                                                                                            }

                                                                                                                                                                    public double CalculateOutput(double[] inputs)
                                                                                                                                                                            {
                                                                                                                                                                                        double sum = 0;
                                                                                                                                                                                                    for (int i = 0; i < inputs.Length; i++)
                                                                                                                                                                                                                {
                                                                                                                                                                                                                                sum += inputs[i] * weights[i];
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                        sum += bias;

                                                                                                                                                                                                                                                                    return activationFunction(sum);
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                    delegate double ActivationFunction(double x);
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                    using System;

                                                                                                                                                                                                                                                                                    namespace NeuralNetwork
                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                        class Neuron
                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                    private double[] weights;
                                                                                                                                                                                                                                                                                                            private double bias;
                                                                                                                                                                                                                                                                                                                    private ActivationFunction activationFunction;

                                                                                                                                                                                                                                                                                                                            public Neuron(int numInputs, ActivationFunction activationFunction)
                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                this.activationFunction = activationFunction;
                                                                                                                                                                                                                                                                                                                                                            weights = new double[numInputs];
                                                                                                                                                                                                                                                                                                                                                                        Random rnd = new Random();

                                                                                                                                                                                                                                                                                                                                                                                    for (int i = 0; i < numInputs; i++)
                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                weights[i] = rnd.NextDouble();
                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                        bias = rnd.NextDouble();
                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                        public double CalculateOutput(double[] inputs)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            double sum = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (int i = 0; i < inputs.Length; i++)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sum += inputs[i] * weights[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sum += bias;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return activationFunction(sum);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        delegate double ActivationFunction(double x);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        